### PR TITLE
Jenkins pipeline: JobDSL set-up and dev/prod jobs

### PR DESCRIPTION
**Pull request by danpaldev**
image

This repository contains two jobs (# 2 and # 3) of the whole task 04.

In a nutshell, job # 2  (**deploy_dev**) is automatically triggered by job # 1 (**thanks_plugin** job) located on the `thank-after-post-plugin` repo. If successful, job # 2  (**deploy_dev**) will automatically trigger job # 3 (**deploy_prod**).

Please see `thank-after-post-plugin` to inspect job #1s code:
https://github.com/korney4eg/thank-after-post-plugin/pull/2

(I created job # 1 separated from the ones in this repo (# 2 and # 3) because I wanted to try a multi-repo Jenkins pipeline)

### CODE REVIEW

**Comment by korney4eg** [comment]
hey @danpaldev could you add me as collaborator in https://github.com/danpaldev/phase02_task04 ?

**Comment by danpaldev** [comment]
> hey @danpaldev could you add me as collaborator in https://github.com/danpaldev/phase02_task04 ?

Done 👍🏼

**Comment by korney4eg** [comment]
hey @danpaldev could you add me as collaborator one more time to https://github.com/danpaldev/phase02_task04 ?

**Comment by danpaldev** [comment]
> hey @danpaldev could you add me as collaborator one more time to https://github.com/danpaldev/phase02_task04 ?

Sure, I just did it again. Tell me if it works

**Pull request closed without merging**
